### ISSUE TITLE
Automation scripts may be failing when replacing {COMMIT} and {HASH} in the README file

### ISSUE THREAD

**Issue by ray-delossantos** [Cloudef/zig-router#4]
I was starting to test this package. Great work!. 

An issue that I found is that maybe the automation pipeline is failing when replacing {COMMIT} and {HASH} values in the README file.

It work as expected if I pickup the corresponding files from the source code but if the dependency setup is easy accessible it may help with library's adoption.

Thanks for a great tool.

**Comment by Cloudef** [comment]
What do you mean by failing? The readme is generated by the flake.nix
Perhaps the instructions could be updated to this style: https://cloudef.github.io/zig-aio/integration

**Comment by ray-delossantos** [comment]
Great. Yes, those instructions are very clear for new users like me :). With that change it makes more sense on how to add the dependency to the `build.zig.zon` file.

**Comment by Cloudef** [comment]
I updated the instructions.
